### PR TITLE
Added macOS binary.

### PR DESCRIPTION
**Pull request by brukberhane**
This is compiled for Intel because that's what I have. But it should do the job just fine.

Edit: Forgot to mention that this is fixing Issue #2

### CODE REVIEW

**Comment by Sewdohe** [comment]
Thanks for much for this my friend!

**Comment by Sewdohe** [comment]
I am almost done with the auto-dependency installer for windows. It will check for a package manager, and if it doesn't find it will install it automatically as well as all the deps for plugins and everything. 

As mentioned, I don't have a mac computer, and couldn't test for when I make the brew scripts...I may come to you for testing if you wouldn't mind.

**Comment by brukberhane** [comment]
I totally don't mind! Let me know how I can be of assistance.

**Comment by Sewdohe** [comment]
> I totally don't mind! Let me know how I can be of assistance.

Awesome! I actually have the entire windows auto-installer working but unfortunately it seems scoop is broken ATM as it's failing the hascheck when trying to install Neovim itself, so I guess  I'll have to wait on that for release of the windows AIO installer, but I think people will really enjoy being able to one click their way to a complete install.

I may start work on the brew scripts tomorrow!

I still can't believe this project grew as fast as it did. Never thought it'd get 70 stars lol

**Comment by brukberhane** [comment]
I actually happened on your project because it showed up on my google news feed. I absolutely love Vim and I'm glad I can help you out with this.

**Comment by Sewdohe** [comment]
> I actually happened on your project because it showed up on my google news feed. I absolutely love Vim and I'm glad I can help you out with this. 

It showed up in your Google news feed?!? 👀👀🤯

well at any rate that's great, and I'm glad someone like you happened along!

Wow, I'm feeling some pressure to get this right fast now 😅

**Comment by brukberhane** [comment]
Don't worry too much. Your project is doing great right now! Besides, people like me that click on Github Repos with interesting descriptions aren't too afraid to get into the code

**Comment by Sewdohe** [comment]
> Don't worry too much. Your project is doing great right now! Besides, people like me that click on Github Repos with interesting descriptions aren't too afraid to get into the code

you're surely right there. I just feel like the repo touts the easyness of it all but Deps are still required to manually install right now and kinda makes it a mess. That's why I'm rushing to get the auto-dep-installer branch done and merged

I feel it'll really take off then

**Pull request merged**
